export const config = {
    VITE_CLERK_PUBLISHABLE_KEY: import.meta.env.VITE_CLERK_PUBLISHABLE_KEY,
    VITE_IMAGE_KIT_ENDPOINT: import.meta.env.VITE_IMAGE_KIT_ENDPOINT,
    VITE_IMAGE_KIT_PUBLIC_KEY: import.meta.env.VITE_IMAGE_KIT_PUBLIC_KEY,
    REACT_APP_CLERK_FRONTEND_API: import.meta.env.REACT_APP_CLERK_FRONTEND_API,
    REACT_APP_CLERK_API_KEY: import.meta.env.REACT_APP_CLERK_API_KEY,
    VITE_GOOGLE_AI_API_KEY: import.meta.env.VITE_GOOGLE_AI_API_KEY
};
